name 'docker_metrics'
maintainer 'Your Name'
maintainer_email 'your.email@example.com'
license 'All Rights Reserved'
description 'Installs/Configures docker containers for metrics collection'
version '0.1.0'
chef_version '>= 14.0'
